version: 2
updates:
  # Monorepo root - handles all npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5  # Reduced from 10
    groups:
      # Group all development dependencies together
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      # Group all production dependencies together  
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "xats-org/maintainers"
    milestone: 4  # v0.4.0 milestone
    # Ignore individual package updates - handled by root
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]  # Ignore patch updates

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"  # Less frequent for actions
      day: "monday"
    open-pull-requests-limit: 2  # Reduced limit
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "component:ci-cd"
    reviewers:
      - "xats-org/maintainers"