name: Security

on:
  push:
    branches: [main, 'v*.*.*']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.claude/**'
      - 'LICENSE'
      - '.github/workflows/!(security).yml'
  pull_request:
    branches: [main, 'v*.*.*']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.claude/**'
      - 'LICENSE'
      - '.github/workflows/!(security).yml'
  schedule:
    # Run security scans weekly on Monday at 2 AM UTC (reduced from daily)
    - cron: '0 2 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.15.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run audit
      run: |
        pnpm audit --audit-level=moderate
        # Generate audit report for all packages
        pnpm --recursive audit --audit-level=moderate || true
      
    - name: Check for outdated dependencies
      run: pnpm outdated || true

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        # Include both javascript and typescript for complete coverage
        language: ['javascript', 'typescript']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  secrets-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Full history for better detection
    
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified

  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.15.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Check licenses
      run: |
        # Install license checker at workspace root
        pnpm add -D -w license-checker
        # Check all package licenses (exclude private packages like monorepo root)
        npx license-checker --production --excludePrivatePackages --summary
        # Fail on problematic licenses (allow these checks to pass for now)
        npx license-checker --production --excludePrivatePackages --failOn 'GPL-3.0;AGPL-3.0;LGPL-3.0' || echo "License check completed with warnings"

  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.15.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run ESLint security plugin
      run: |
        # Install security plugin at workspace root if not present
        pnpm add -D -w eslint-plugin-security
        # Run security-focused linting
        pnpm run lint || true

  sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest
    # Only generate SBOM on releases and main branch pushes
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.15.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: sbom.spdx.json
      
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.spdx.json
        retention-days: 30

